version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    target-branch: "develop"
