version: "3.8"

services:
  nginx:
    depends_on:
      - api
      # - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  mongodb:
    image: mongo:latest
    ports:
      - "27777:27017"
    volumes:
      - ./db/cook-dev:/data/db

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./api"
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URL: mongodb://mongodb:27017/cook-dev
      SECRET_KEY: (*)(*^**))
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    ports:
      - ${PORT:-3001}:3001