version: "3.8"

services:
  nginx:
    depends_on:
      - api
      - web
      # - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
      - "8081:4000"

  mongodb:
    image: mongo:latest
    ports:
      - "27777:27017"
    volumes:
      - ./db/cook-dev:/data/db

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./api"
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URL: mongodb://mongodb:27017/cook-dev
      SECRET_KEY: (*)(*^**))
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    # ports:
    #   - ${PORT:-3001}:3001

  web:
    build:
      dockerfile: Dockerfile.dev
      context: "./web"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    volumes:
      - /usr/src/web/node_modules
      - ./web:/usr/src/web
    # ports:
    #   - ${PORT:-3000}:3000