version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./api"
    environment:
      PORT: 3001
      NODE_ENV: development
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    ports:
      - ${PORT:-3001}:3001