name: Build and Test

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build_and_test_api:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: [16,17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: switch to srouce api
        run: cd api
      - name: Install project
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Lint
        run: npm run lint

