name: Build and Test API

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build_and_test_api:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dir: ['api']
        node: [16]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        working-directory: ${{ matrix.dir }}
        run: npm install
      - name: Build the project
        working-directory: ${{ matrix.dir }}
        run: npm run build
      - name: Lint
        working-directory: ${{ matrix.dir }}
        run: npm run lint

  build_and_test_web:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dir: ['web']
        node: [16]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        working-directory: ${{ matrix.dir }}
        run: npm install
      - name: Build the project
        working-directory: ${{ matrix.dir }}
        run: npm run build
      - name: Lint
        working-directory: ${{ matrix.dir }}
        run: npm run lint

